package:
  name: nirmapper
  version: "v0.1.1"

source:
  git_rev: v0.1.1
  git_url: https://github.com/fechbmaster/3DNIRmapper.git
  path: $RECIPE_DIR/../..

requirements:
  build:
    - python
    - setuptools
    - numpy
    - pywavefront
  run:
    - python

test:
  imports:
    - nirmapper

about:
  home: https://github.com/fechbmaster/3DNIRmapper
  license: Apache-2.0
  license_file: LICENSE