package:
  name: nirmapper
  version: "v1.0"

source:
  git_rev: v1.0
  git_url: https://github.com/fechbmaster/3DNIRmapper.git


requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy

test:
  imports:
    - nirmapper

about:
  home: https://github.com/fechbmaster/3DNIRmapper
  license: Apache-2.0
  license_file: LICENSE