package:
  name: nirmapper
  version: "v1.1"

source:
  git_url: https://github.com/fechbmaster/3DNIRmapper.git


requirements:
  build:
    - python
    - numpy
    - pip
  run:
    - python
    - numpy

about:
  home: https://github.com/fechbmaster/3DNIRmapper
  license: Apache-2.0
  license_file: LICENSE